name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout master
         uses: actions/checkout@v2
         with:
           ref: master

       - name: Setup node
         uses: actions/setup-node@v1
         with:
          node-version: "14"

       - name: Build project
         run: yarn && yarn build

       - name: Release
         run: yarn release
         env:
           NPM_TOKEN: ${{ secrets.NPM }}
           GITHUB_TOKEN: ${{ secrets.GIT }}